services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fiware

  orion:
    image: telefonicaiot/fiware-orion
    container_name: orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo:27017 -logLevel DEBUG
    networks:
      - fiware

  crate:
    image: crate/crate:latest
    container_name: crate
    ports:
      - "4200:4200"
      - "5432:5432"
    command:
      [
        "crate",
        "-Cdiscovery.type=single-node",
        "-Ccluster.name=docker-cluster",
        "-Cgateway.expected_nodes=1",
        "-Cgateway.recover_after_nodes=1",
      ]
    environment:
      - CRATE_HEAP_SIZE=1g
    volumes:
      - crate_data:/data
    networks:
      - fiware

  quantumleap:
    image: orchestracities/quantumleap:latest
    container_name: quantumleap
    depends_on:
      - crate
      - orion
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate
      - QL_CRATE_HOST=crate
      - CRATE_PORT=4200
      - QL_DB_NAME=doc
      - USE_GEOCODING=False
      - LOGLEVEL=INFO
    networks:
      - fiware

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - crate
    networks:
      - fiware

  openmeteo_adapter:
    build: ./open_meteo
    container_name: openmeteo_adapter
    environment:
      - ORION_HOST=http://orion:1026
      - LATITUDE=-5.795
      - LONGITUDE=-35.195
      - CITY_NAME=Natal
      - REFRESH_INTERVAL_SECONDS=60
      - FIWARE_SERVICE=openmeteo_service
      - FIWARE_SERVICE_PATH=/weather
      - ENTITY_ID=WeatherObserved:Natal
      - PYTHONUNBUFFERED=1
    depends_on:
      - orion
    networks:
      - fiware

volumes:
  mongo-data:
  grafana-storage:
  crate_data:

networks:
  fiware:
